services:
  backend:
    build: ./backend
    container_name: rumsense-backend
    ports:
      - "8000:8000" # API
      - "7000:7000/udp" # Nooploop UDP Ingest
    volumes:
      - ./backend:/app
    restart: always
    networks:
      - rumsense-net

  frontend:
    build:
      context: ./frontend
      target: development
    container_name: rumsense-frontend

    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - rumsense-net

  nginx:
    image: nginx:alpine
    container_name: rumsense-nginx
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
    networks:
      - rumsense-net

networks:
  rumsense-net:
    driver: bridge
